baseurl: konkanant

target: _site

collections:
  - name: posts
    folder: _posts
  - name: books
    folder: _books

data:
  - _data

pageviews:
  - _pages

exclude:
  - gulpfile.js
  - package.json
  - miner

theme: bootstrap
debug: true

title: Καναβούρας Κωνσταντίνος
