name: first-github-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download stakx
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "stakx-io/stakx"
          version: "tags/v0.2.1"
          file: "stakx-0.2.1.phar"
          target: "stakx.phar"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Store personal YML configuration
        run: 'echo "$PERSONAL_YML" > _data/personal.yml'
        shell: bash
        env:
          PERSONAL_YML: ${{ secrets.PERSONAL_YML }}

      - name: Build website
        run: php stakx.phar build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KEYSCAN }}

      - name: Deploy with rsync
        run: rsync -navz ./_site/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }}:REMOTE_DIRECTORY

      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x

      # - name: Build
      #   run: |
      #     npm install
      #     gulp sass