name: first-github-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download stakx
        uses: wei/curl@master
        with:
          args: https://github.com/stakx-io/stakx/releases/download/v0.2.1/stakx-0.2.1.phar -o stakx.phar

      # - name: Download stakx
        # run: curl https://github.com/stakx-io/stakx/releases/download/v0.2.1/stakx-0.2.1.phar -o stakx.phar

      - name: Build website
        run: php stakx.phar build

      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x

      # - name: Build
      #   run: |
      #     npm install
      #     gulp sass